config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :events
    resources :users
    resources :departments
    resources :banners
    resources :sponsors
    root to: "events#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  resources :events, only: [:index]
  resources :workers, only: [:index]
  resources :sponsors, only: [:index]

  get 'search', to: "search#index", as: "search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :image, BannerImageUploader
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users,  -> { order "priority ASC" }
  mount_uploader :image, EventImageUploader
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, EventImageUploader
  has_and_belongs_to_many :users
  scope :all_except, ->(exception) { where.not(id: exception) }
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  mount_uploader :picture, SponsorImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable, :rememberable

  mount_uploader :avatar, AvatarUploader
  belongs_to :department,  optional: true
  has_and_belongs_to_many :events
  scope :all_except, ->(exception) { where.not(id: exception) }

  def is_admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:current_password,:motto, :password, :password_confirmation, :avatar, :jobs)}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @music_events = Event.where("category"=>"歌").order("priority" => "asc")
    @dance_events = Event.where("category"=>"舞").order("priority" => "asc")
    @drama_events = Event.where("category"=>"劇").order("priority" => "asc")
    @light_events = Event.where("category"=>"光").order("priority" => "asc")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:name].length == 2
      @user = User.where('name LIKE ?', ("#{params[:name].first}"+"　"+"#{params[:name].last}")).includes(:events).first 
    else
      @user = User.where('name LIKE ?', "#{params[:name]}").includes(:events).first 
    end
    if @user.present?
      if @user.events.present?
        time = @user.events.order("schedule" => "asc").first.schedule.split('-').first.to_time
        @arrive_time = (time.to_time-10*60).strftime("%H:%M")
      else
        @arrive_time = "18:00"
      end
      @recommend = Event.all_except(@user.events).sample
      @friend = User.all_except(@user).sample
    else
      @recommend = Event.all.sample
      @friend = User.all.sample
    end
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def index
    @sponsors = Sponsor.order("donate" => "desc")
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @departments = Department.order("order" => "asc").includes(:users)
    @events = Event.order("priority" => "asc").includes(:users)
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def render_anchor(event)
    case event.title
    when "大一民謠"
      "freshman-music"
    when "大二民謠"
      "sophomore-music"
    when "大三民謠"
      "junior-music"
    when "大四民謠"
      "senior-music"
    when "跨界民謠"
      "cross-music"
    when "大一舞"
      "freshman-dance"
    when "大二舞"
      "sophomore-dance"
    when "大三舞"
      "junior-dance"
    when "大四舞"
      "senior-dance"
    when "女舞"
      "girls-dance"
    when "男舞"
      "boys-dance"
    when "大一劇"
      "freshman-drama" 
    when "串場劇"
      "cross-drama" 
    when "光舞"
      "light"
    else
      "music"
    end    
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
  def render_motto(user)
    if user.motto.present?
      return "「#{user.motto}」-- #{user.name} "
    end
  end
end

app/views/fields/ck_editor_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.cktext_area field.attribute, cols: 40, ckeditor: {uiColor: '#2a94d6', toolbar: 'mini'} %>
</div>

app/views/fields/ck_editor_field/_index.html.erb
<%= field.to_s %>

app/views/fields/ck_editor_field/_show.html.erb
<%= field.to_s %>

app/views/fields/image_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute %>
</div>

app/views/fields/image_field/_index.html.erb
<%= image_tag field.thumb %>

app/views/fields/image_field/_show.html.erb
<%= image_tag field.small %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115190284-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-115190284-1');
    </script>

    <title>2018資訊之夜-念茲在資 | mo shíorghrá</title>
    <meta property="og:title" content="2018資訊之夜 念茲在資mo shíorghrá" />
    <meta property="og:image" content="https://nightweb.csie.org/img/cover.jpg" />
    <meta property="og:description" content="
      時間在日記扉頁留下墨跡，
      走過路過風光旖旎，
      過往雲煙總是美得無可挑剔，
      沈浸在回憶裡歇息，
      才發現那些情，已無蹤跡..." />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="img/cover-small.ico">
  </head>

  <body>
    <%= render "partials/navbar" %>
    <%= render "partials/flashes" %>
    <%= yield %>
  </body>
  <%= render "partials/footer" %>
  <script src="js/jquery.easing.min.js"></script>
  <script src="js/smooth-scrolling.js"></script>
  <script src="js/ScrollTrigger.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.0/jquery.waypoints.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function(){
      var trigger = new ScrollTrigger();
    });
    $('body').bind('touchstart',function(){});
    (function ($) {
      $(function () {
        $('.evt_scroll-section').scrollIndicatorBullets({
          titleSelector: 'h1,h2,h3'
        });
      });
    })(jQuery);
  </script>
</html>
    

app/views/pages/index.html.erb
<header class="masthead text-center" id="top">
  <div class="col-md-5 p-lg-5 mx-auto my-5"
 data-scroll="toggle(.scaleDownIn, .scaleDownOut)">
    <div class="container" id="index-title"></div>
    <a class="btn btn-outline-secondary" href="#about">More</a>
  </div>
  <div class="overlay"></div>
</header>
<!-- About -->
<section class="content-section" id="about">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"
          data-scroll="toggle(.fromRightIn, .fromRightOut)">念茲，在資</h1>
      <p class="lead"
         data-scroll="toggle(.fromLeftIn, .fromLeftOut)">2018 資訊之夜 mo shíorghrá</p>
      <hr class="my-4">
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">泛黃的照片，逐漸褪色無光。</p>   
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">黯淡的四周，只剩前方路上車尾燈明晃晃。</p>    
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">夢裡笑靨逐開，是那般真實。</p>   
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">伸出手，一切卻早已太遲。</p>    
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">時間在日記扉頁留下墨跡，</p>    
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">走過路過風光旖旎，</p>   
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">過往雲煙總是美得無可挑剔，</p>   
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">沈浸在回憶裡歇息，</p>
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">突破緊繃的外殼才發現那些情，已無蹤跡。</p>
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">曾經汲汲營營晉代衣冠，</p>
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">如今滄海桑田成古坵。</p>
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">別擔心，</p>
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">念茲在茲的窮極盡頭，</p>
      <p data-scroll="toggle(.fromLeftIn, .fromLeftOut)">是我們一起，念茲，在資。</p>
      <hr class="my-4">
      <p class="lead" data-scroll="toggle(.fromLeftIn, .fromLeftOut)">有人看了一眼，卻惦念了一生</p>
    </div>
  </div>
</section>

    <!-- Performance -->
<section class="content-section" id="performance">
  <div class="container">
    <h1 class="display-4 text-center"
      data-scroll="toggle(.fromTopIn, .fromTopOut)"
      id="performance-title">Performance
    </h1>
    <div class="row no-gutters">

      <div class="col-lg-6">
        <%= link_to(events_path(anchor: "music"), class: "portfolio-item", :data => { :reload => true } ) do %>
            <span class="caption">
              <span class="caption-content">
                <!-- Song-->
                <img src="img/performance/white-song.png" alt="">
                <p class="mb-0">大一民謠|大二民謠|大三民謠|大四民謠|跨屆民謠</p>
              </span>
            </span>
            <img class="img-fluid" src="img/performance/img-song.jpg" alt="">

        <% end %>
      </div>

      <div class="col-lg-6">
        <%= link_to(events_path(anchor: "dance"), class: "portfolio-item", :data => { :reload => true } ) do %>
          <span class="caption">
            <span class="caption-content">
              <!-- Dance-->
              <img src="img/performance/white-dance.png" alt="">
              <p class="mb-0">大一舞|大二舞|大三舞|大四舞|男女舞</p>
            </span>
          </span>
          <img class="img-fluid" src="img/performance/img-dance.jpg" alt="">
        <% end %>
      </div>

      <div class="col-lg-6">
        <%= link_to(events_path(anchor: "drama"), class: "portfolio-item", :data => { :reload => true } ) do %>
          <span class="caption">
            <span class="caption-content">
              <!-- Drama-->
              <img src="img/performance/white-drama.png" alt="">
              <p class="mb-0">大一劇|串場劇</p>
            </span>
          </span>
          <img class="img-fluid" src="img/performance/img-drama.jpg" alt="">
        <% end %>
      </div>

      <div class="col-lg-6">
        <%= link_to(events_path(anchor: "light"), class: "portfolio-item", :data => { :reload => true } ) do %>
          <span class="caption">
            <span class="caption-content">
              <!-- Light-->
              <img src="img/performance/white-light.png" alt="">
              <p class="mb-0">螢光舞</p>
            </span>
          </span>
          <img class="img-fluid" src="img/performance/img-light.jpg" alt="">
        <% end %>
      </div>
    </div>
  </div>
</section>

<!-- Schedule -->
<section class="content-section" >
  <div class="jumbotron jumbotron-fluid" id="schedule">
    <div class="container">
      <h1 class="display-4 text-center"
          data-scroll="toggle(.fromTopIn, .fromTopOut)">Schedule
      </h1>
    </div>
    <div class="container">
      <div class="row">
        <table class="table table-schedule lead">
          <thead>
      <tr>
        <th colspan="2" class="mid-col" data-scroll="toggle(.fromLeftIn, .fromLeftOut)">上半場</th>
      </tr>
          </thead>
          <tbody>
      <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
        <td>大二舞</td>
        <td class="right-col">18:00-18:08</td>
      </tr>
      <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
        <td>大三舞</td>
        <td class="right-col">18:10-18:15</td>
      </tr>
      <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
        <td>大一劇</td>
        <td class="right-col">18:20-18:55</td>
      </tr>
      <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
        <td>男女舞</td>
        <td class="right-col">19:00-19:08</td>
      </tr>
      <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
        <td>大一民謠</td>
        <td class="right-col">19:13-19:28</td>
      </tr>
      <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
        <td>大四舞</td>
        <td class="right-col">19:33-19:41</td>
      </tr>
          </tbody>
        </table>
        <table class="table table-schedule lead">
          <thead>
      <tr>
        <th colspan="2" class="mid-col"
            data-scroll="toggle(.fromRightIn, .fromRightOut)">下半場</th>
      </tr>
          </thead>
          <tbody>
      <tr data-scroll="toggle(.fromRightIn, .fromRightOut)">
        <td>跨屆民謠</td>
        <td class="right-col">19:55-20:20</td>
      </tr>
      <tr data-scroll="toggle(.fromRightIn, .fromRightOut)">
        <td>大一舞</td>
        <td class="right-col">20:25-20:33</td>
      </tr>
      <tr data-scroll="toggle(.fromRightIn, .fromRightOut)">
        <td>男女舞</td>
        <td class="right-col">20:35-20:43</td>
      </tr>
      <tr data-scroll="toggle(.fromRightIn, .fromRightOut)">
        <td>跨屆民謠</td>
        <td class="right-col">20:48-21:18</td>
      </tr>
      <tr data-scroll="toggle(.fromRightIn, .fromRightOut)">
        <td>光舞</td>
        <td class="right-col">21:20-21:30</td>
      </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="container">
      <h1 class="display-4 text-center"
        data-scroll="toggle(.fromTopIn, .fromTopOut)">Map</h1>
    </div>
    <div class="container" id="map"></div>
    <div class="container">
      <table class="table lead" id="time-and-place">
        <thead>
          <tr>
      <th colspan="2" data-scroll="toggle(.fromLeftIn, .fromLeftOut)">資訊之夜 念茲在資 mo shíorghrá</th>
          </tr>
        </thead>
        <tbody>
          <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
      <td>時間</td>
      <td>2018/3/29（四）18:00</td>
          </tr>
          <tr data-scroll="toggle(.fromLeftIn, .fromLeftOut)">
      <td>地點</td>
      <td>國立臺灣大學 第一學生活動中心 怡仁堂（活大禮堂）</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/pages/worker.html.erb
<h1>工作人員</h1>
<% @departments.each do |department| %>
  <h2><%= department.name %></h2>   
  <br>
  <% department.users.each do |user| %>
    <h3><%= user.name %></h3>   
    <%= image_tag(user.avatar.small) %>
    <p><%= user.motto %></p> 
  <% end %>
<% end %>


<h1>表演人員</h1>
<% @events.each do |event| %>
  <h2><%= event.title %></h2>
  <% event.users.each do |user| %>
    <h3><%= user.name %></h3>   
    <%= image_tag(user.avatar.small) %>
    <p><%= user.motto %></p> 
  <% end %>
<% end %>

app/views/partials/_event.html.erb
<% events.each do |event| %>
  <section class="evt_nav_section" id="<%= render_anchor(event) %>">
    <div class="evt_img-container">
      <%= image_tag(event.image_url.to_s, class: "evt_img") %>
    </div>
    <div class="evt_content">
      <div class="evt_inner">
        <header>
          <h3><%= event.title %></h3>
        </header>
        <p>
          <%= event.introduction.html_safe %>
        </p>
      </div>
    </div>
  </section>
<% end %>

app/views/partials/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/partials/_footer.html.erb
<footer class="footer bg-footer-color">
	<div class="footer-content">
	  <span class="text-muted">
	    Copyright &copy; <%= link_to "CSIENIGHT", edit_user_registration_path %> 2018 台大資訊工程學系 - 資訊之夜學術部  保留一切權利<br>
	    Web Designed and Developed By CSIE NIGHT 學術部
	  </span>
	</div>
</footer>

app/views/partials/_navbar.html.erb
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" id="navbarExpand">
  <%= link_to("mo shíorghrá", root_path(anchor: "top"), class: "navbar-brand") =%>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to("Performance", root_path(anchor: "performance"), class: "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to("Info", root_path(anchor: "schedule"), class: "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to("Contributors", workers_path, class: "nav-link" ) %>
      </li>
      <li class="nav-item">
        <%= link_to("Sponsors", sponsors_path, class: "nav-link") %>
      </li>
      <li class="nav-item">
        <a href="https://www.facebook.com/2018.CSIE.night/" class="nav-link">Facebook</a>
      </li>

    </ul>
      <%= form_tag search_path,:class => "form-inline mt-2 mt-md-0", method: :get do %>
        <%= text_field_tag :name, params[:name], placeholder: "輸入好友姓名",:class => "form-control mr-sm-2 search" %>
        <%= submit_tag "Search", name: nil, :class => " btn-outline-success search-btn my-2 my-sm-0" %>
      
      <% end %>
    
  </div>
</nav>